version: "3.9"

services:
  api:
    build:
      context: .
    image: maio-assignment3:local
    ports:
      - "8080:8080"
    environment:
      MODEL_PATH: /app/models/model_v0.2.joblib
      METRICS_PATH: /app/models/metrics_v0.2.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
