name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint (optional)
        run: |
          pip install flake8
          flake8 .
      - name: Run tests
        run: pytest -q

  train-upload-and-smoketest:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train baseline model (v0.1)
        run: python -m src.train --version v0.1 --model linear --out_dir models --random_state 42
      - name: Show metrics file
        run: cat models/metrics_v0.1.json
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-v0.1
          path: models/model_v0.1.joblib
      - name: Build Docker image
        run: docker build -t triage:${{ github.sha }} .
      - name: Run container (smoke test)
        run: |
          docker run -d --name triage_test -p 8080:8080 triage:${{ github.sha }}
          sleep 3
          curl -f -X GET http://localhost:8080/health
          # quick sample payload (returns 200)
          curl -f -X POST http://localhost:8080/predict -H "Content-Type: application/json" -d '[{"age":0,"sex":0,"bmi":0,"bp":0,"s1":0,"s2":0,"s3":0,"s4":0,"s5":0,"s6":0}]'
        shell: bash
